[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
  let g:fern#default_hidden=1
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
  let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup END
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
depends_on = ['coc.nvim']
hook_add = '''
let g:lightline = {
\ 'colorscheme': 'iceberg',
\ 'active': {
\   'left': [
\     [ 'coc'],
\     [ 'mode', 'paste' ],
\     ['readonly', 'filename', 'modified']
\    ],
\   'right': [
\     [ 'lineinfo' ],
\     [ 'fileformat', 'fileencoding', 'filetype' ]
\    ]
\ },
\ 'component_fuction': {
\   'coc': 'coc#status'
\ }
\ }
'''

[[plugins]]
repo = "neoclide/coc.nvim"
merged = 0
rev = "release"

[[plugins]]
repo = 'airblade/vim-gitgutter'
