[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
source $XDG_CONFIG_HOME/nvim/plugins/fern.vim
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
  let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup END
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
depends_on = ['coc.nvim']
hook_add = '''
let g:lightline = {
\ 'colorscheme': 'iceberg',
\ 'active': {
\   'left': [
\     [ 'coc'],
\     [ 'mode', 'paste' ],
\     ['readonly', 'filename', 'modified']
\    ],
\   'right': [
\     [ 'lineinfo' ],
\     [ 'fileformat', 'fileencoding', 'filetype' ]
\    ]
\ },
\ 'component_fuction': {
\   'coc': 'coc#status'
\ }
\ }
'''

[[plugins]]
repo = "neoclide/coc.nvim"
merged = 0
rev = "release"
hook_add = '''
source $XDG_CONFIG_HOME/nvim/plugins/coc.vim
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends_on = ['plenary.nvim']
hook_add = '''
nnoremap <Leader>ff <cmd>Telescope find_files hidden=true<CR>
nnoremap <Leader>fg <cmd>Telescope live_grep<CR>
nnoremap <Leader>fb <cmd>Telescope buffers<CR>
'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'itchyny/vim-parenmatch'
